//
//  StringsVariableGenerator.swift
//
//
//  Created by Neel Kumar on 12/7/23.
//

import Foundation

internal protocol StringsVariableGeneratorProtocol {
    func generate()
}

internal final class StringsVariableGenerator: StringsVariableGeneratorProtocol {
    
    let localizationDirectoryPath: String
    let primaryLanguageData: [String: String]
    
    private let fileManager = FileManager.default

    init(localizationDirectoryPath: String, primaryLanguageData: [String: String]) {
        self.localizationDirectoryPath = localizationDirectoryPath
        self.primaryLanguageData = primaryLanguageData
    }
    
    // auto generate the localizable file
    func generate() {
        let directory = URL(fileURLWithPath: localizationDirectoryPath)
        let filePath = directory.appendingPathComponent("LocalizableStrings.swift")
        
        let writeText = generateNewVariablesFileString()
        
        do {
            if !fileManager.fileExists(atPath: filePath.path) {
                // throw large fatal error, file does not exist for code
                fileManager.createFile(atPath: filePath.path, contents: nil, attributes: nil)
            }
            try writeText.write(to: filePath, atomically: true, encoding: String.Encoding.utf8)
            print("[SL LOG]: successfully generated new LocalizableStrings")
        } catch let error {
            print("[SL ERROR]: ", error)
        }
    }
    
    func generateNewVariablesFileString() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "HH:mm E, d MMM y"
        let dateString = formatter.string(from: Date())
        
        var swiftCodeToWrite = """
        // Autogenerated at \(dateString). Do not modify\n\n
        import Foundation

        struct LocalizableStrings {
        
        """
        
        for key in primaryLanguageData.keys {
            swiftCodeToWrite += "\tstatic let \(key) = NSLocalizedString(\"\(key)\", comment: \"Localizable\")\n"
        }
        
        swiftCodeToWrite += "\n}"
        // TODO: run the ruby script manually
        // https://chat.openai.com/share/180711d5-b197-4152-8080-7790b996a1cc
        return swiftCodeToWrite
    }
}
