//
//  Translater.swift
//
//
//  Created by Neel Kumar on 12/7/23.
//

import Foundation

protocol TranslaterProtocol {
    func generateNewLanguageFileString(primaryLanguageData: [String: String], languageCode: String) -> String
}

final class Translater: TranslaterProtocol {
    
        
    func generateNewLanguageFileString(primaryLanguageData: [String: String], languageCode: String) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "HH:mm E, d MMM y"
        var generatedString = "// Autogenerated at " + formatter.string(from: Date()) + ". Do not modify\n\n"
        
        for key in primaryLanguageData.keys {
            // TODO: localize the values here and store them
            if let value = primaryLanguageData[key] {
                generatedString += "\"\(key)\" = \"\(value)\";\n"
            } else {
                generatedString += "\"\(key)\" = \"\";\n"
            }
        }
        
        return generatedString
    }
}
