//
//  Translater.swift
//
//
//  Created by Neel Kumar on 12/7/23.
//

import Foundation

internal protocol TranslaterProtocol {
    func generateNewLanguageFileString(primaryLanguageData: [String: String], languageCode: String) -> String
}

internal final class Translater: TranslaterProtocol {
    
    // TODO: initalize this varaibles
    //primaryLanguageData: [String: String]
    //languageCode: String
    
    func generateNewLanguageFileString(primaryLanguageData: [String: String], languageCode: String) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "HH:mm E, d MMM y"
        var generatedString = "// Autogenerated at " + formatter.string(from: Date()) + ". Do not modify\n\n"
        
        // TODO: localize the values here and store themm make API call...
        
        for key in primaryLanguageData.keys {
            if let value = primaryLanguageData[key] {
                generatedString += "\"\(key)\" = \"\(value)\";\n"
            } else {
                generatedString += "\"\(key)\" = \"\";\n"
            }
        }
        
        getLocalizedData(primaryLanguageData, languageCode)
        Thread.sleep(forTimeInterval: 5.0)
        return generatedString
    }
    
    func getLocalizedData(_ primaryLanguageData: [String: String], _ languageCode: String) {
        // Example usage
        let response = API.makeAPIRequest(primaryLanguageData, languageCode)
        print("Response: \(response)")
    }
}
