//
//  Translater.swift
//
//
//  Created by Neel Kumar on 12/7/23.
//

import Foundation

internal protocol TranslaterProtocol {
    func generateNewLanguageFileString(primaryLanguageData: [String: String], languageCode: String, completion: @escaping(_ fileString: String) -> Void)
}

internal final class Translater: TranslaterProtocol {
    
    let openAPIKey: String
    
    init(openAPIKey: String) {
        self.openAPIKey = openAPIKey
    }
    
    func generateNewLanguageFileString(primaryLanguageData: [String: String], languageCode: String, completion: @escaping(_ fileString: String) -> Void) {
        let formatter = DateFormatter()
        formatter.dateFormat = "HH:mm E, d MMM y"
        var generatedString = "// Autogenerated at " + formatter.string(from: Date()) + ". Do not modify\n\n"
    
        API(openAPIKey: openAPIKey)
            .makeAPIRequest(primaryLanguageData, languageCode) { localizedData in
            for key in localizedData.keys {
                if let value = localizedData[key] {
                    generatedString += "\"\(key)\" = \"\(value)\";\n"
                } else {
                    generatedString += "\"\(key)\" = \"\";\n"
                }
            }
            completion(generatedString)
        }
    }
}
